Acme\StoreBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: Acme\StoreBundle\Entity\ProductRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        price:
            type: float
    lifecycleCallbacks: {  }
