Reservable\ActivityBundle\Document\Activity:
    fields:
        id:
            id:  true
        active:
            type: int
        name:
            type: string
        price:
            type: float
        typeRent:
            type: string
        ownerID:
            type: string
        address:
            type: string
        lat:
            type: float
        long:
            type: float
        description:
            type: string
        feature:
            type: string