Reservable\ActivityBundle\Document\Activity:
    fields:
        id:
            id:  true
        name:
            type: string
        price:
            type: float
        typeRent:
            type: string
        ownerID:
            type: string