reservable_activity_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ReservableActivityBundle:Default:index }

new_reservable_activity:
    pattern:  /new-activity
    defaults: { _controller: ReservableActivityBundle:Default:createActivity }

submitActivity:
    pattern:  /submit-activity
    defaults: { _controller: ReservableActivityBundle:Default:submitActivity }

ActivityRegistered:
    pattern:  /activityRegistered
    defaults: { _controller: ReservableActivityBundle:Default:activityRegistered }