reservable_activity_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ReservableActivityBundle:Default:index }

new_reservable_activity:
    pattern:  /new-activity
    defaults: { _controller: ReservableActivityBundle:Default:createActivity }

submitActivity:
    pattern:  /submit-activity
    defaults: { _controller: ReservableActivityBundle:Default:submitActivity }

ActivityRegistered:
    pattern:  /activityRegistered
    defaults: { _controller: ReservableActivityBundle:Default:activityRegistered }

ViewActivities:
    pattern:  /view-instalations
    defaults: { _controller: ReservableActivityBundle:Default:viewActivities }

modifyActivities:
    pattern:  /modify-instalations
    defaults: { _controller: ReservableActivityBundle:Default:modifyActivities }

UploadPicture:
    pattern: /upload-picture
    defaults: { _controller: ReservableActivityBundle:Default:uploadFile }

submitPicture:
    pattern: /submit-picture
    defaults: { _controller: ReservableActivityBundle:Default:submitUploadFile }

pictureUploaded:
    pattern: /picture-uploaded
    defaults: { _controller: ReservableActivityBundle:Default:pictureUploaded }

instalationCalendar:
    pattern: /calendar
    defaults: { _controller: ReservableActivityBundle:Default:calendar }

deleteActivity:
    pattern: /delete-activity
    defaults: { _controller: ReservableActivityBundle:Default:deleteActivity }
