parameters:
#    reservable_activity.example.class: Reservable\ActivityBundle\Example

services:
#    reservable_activity.example:
#        class: %reservable_activity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
