parameters:
#    user_new_user.example.class: UserNew\UserBundle\Example

services:
#    user_new_user.example:
#        class: %user_new_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    user_new_user.registration.form.type:
        class: UserNew\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: user_new_user_registration }
