prueba_probando_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PruebaProbandoBundle:Default:index }

mail:
    pattern:  /mail
    defaults: { _controller: PruebaProbandoBundle:Default:enviarMail }
